create table TOKENS
(
    ID            VARCHAR(40)  PRIMARY KEY,-- UUID를 기본값으로 설정
    REFRESH_TOKEN VARCHAR(255) NOT NULL,   -- 리프레시 토큰
    CREATED_AT    TIMESTAMP    NOT NULL,   -- 생성 날짜, 기본값은 현재 시간
    CREATED_BY    VARCHAR(40)  NOT NULL,   -- 만든 사람의 UUID
    MODIFIED_AT   TIMESTAMP    NOT NULL,   -- 수정 날짜, 기본값은 현재 시간
    MODIFIED_BY   VARCHAR(40)  NOT NULL    -- 수정한 사람의 UUID
);

COMMENT ON TABLE TOKENS IS '토큰 정보를 저장하는 테이블';
COMMENT ON COLUMN TOKENS.ID IS 'PK - 토큰 UUID';
COMMENT ON COLUMN TOKENS.REFRESH_TOKEN IS 'REFRESH TOKEN';
COMMENT ON COLUMN TOKENS.CREATED_AT IS '토큰 정보 생성일';
COMMENT ON COLUMN TOKENS.CREATED_BY IS '토큰 정보 생성자';
COMMENT ON COLUMN TOKENS.MODIFIED_AT IS '토큰 정보 생성자';
COMMENT ON COLUMN TOKENS.MODIFIED_BY IS '토큰 정보 생성자';